export default [
    {
        files: ["site/js/**/*.js"],
        languageOptions: {
            ecmaVersion: 5,
            sourceType: "script",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                fetch: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                HTMLElement: "readonly",
                Event: "readonly",
                CustomEvent: "readonly",
                IntersectionObserver: "readonly",
                MutationObserver: "readonly",
                ResizeObserver: "readonly",
                navigator: "readonly",
                location: "readonly",
                history: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                performance: "readonly",
                alert: "readonly",
                confirm: "readonly",
                prompt: "readonly",
                getComputedStyle: "readonly",
                matchMedia: "readonly",
                queueMicrotask: "readonly",
                AVCharts: "readonly",
                Promise: "readonly",
            },
        },
        rules: {
            "no-undef": "error",
            "no-unused-vars": ["warn", { vars: "local", args: "none" }],
            "no-redeclare": "error",
            "eqeqeq": ["error", "smart"],
            "no-implicit-globals": "error",
            "no-var": "off",
            "prefer-const": "off",
            "strict": ["error", "function"],
            "no-eval": "error",
            "no-implied-eval": "error",
            "no-new-func": "error",
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-throw-literal": "error",
            "no-unmodified-loop-condition": "error",
            "no-useless-concat": "warn",
            "no-useless-return": "warn",
            "curly": ["error", "multi-line"],
            "no-shadow": "warn",
        },
    },
];
